### ISSUE TITLE
Input field for password type is “text”

### ISSUE THREAD

**Issue by MiguelLeyesa** [Skentir/LayerTech-v2.0#36]
Date: Jan 15, 2021
By: Team Blended-not-Stirred
Branch: main
Browser: Firefox

Type: 
(Coding Error / **Design Issue** / Suggestion)

Severity: 
(Fatal / Serious / **Minor**)

Screenshot:
![image](https://user-images.githubusercontent.com/61416986/104695023-0ac66200-5747-11eb-964b-908cd19593ef.png)

Description:
The text in the password field in the login page is seen. 

Steps to Replicate:
1. Go to http://localhost:8080/#/
1. Type anything in the password field

Suggested Fix (Optional):
Change the type attribute for the input field to “password”

**Comment by rainecortel** [comment]
DATE: January 18, 2021

BY: Howard & Friends

BRANCH: Main

BROWSER: Google Chrome Version 87.0.4280.141 (64-bit)

TYPE:
(Coding Error / **Design Issue** / Suggestion)

SEVERITY:
(Fatal / Serious / **Minor**)

DESCRIPTION:
The password for logging in is visible instead of being hidden.

STEPS TO REPLICATE:
1. Run the application on localhost:8080.
2. Enter the provided password credentials.

EXPECTED RESULTS:
The password input text should remain hidden.

ACTUAL RESULTS:
The password input text is visible.

SCREENSHOTS:
![image](https://user-images.githubusercontent.com/61410465/104915026-001bff00-59cb-11eb-9396-e41f821dae15.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
